// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kudos/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.GoGoProtoPackageIsVersion3

// QueryKudosBalanceRequest is the request for querying kudos balance
type QueryKudosBalanceRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryKudosBalanceRequest) Reset()         { *m = QueryKudosBalanceRequest{} }
func (m *QueryKudosBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryKudosBalanceRequest) ProtoMessage()    {}

// QueryKudosBalanceResponse is the response for kudos balance query
type QueryKudosBalanceResponse struct {
	Balance uint64 `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (m *QueryKudosBalanceResponse) Reset()         { *m = QueryKudosBalanceResponse{} }
func (m *QueryKudosBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryKudosBalanceResponse) ProtoMessage()    {}

// QueryKudosLeaderboardRequest is the request for querying leaderboard
type QueryKudosLeaderboardRequest struct {
	Limit uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (m *QueryKudosLeaderboardRequest) Reset()         { *m = QueryKudosLeaderboardRequest{} }
func (m *QueryKudosLeaderboardRequest) String() string { return proto.CompactTextString(m) }
func (*QueryKudosLeaderboardRequest) ProtoMessage()    {}

// LeaderboardEntry represents a single leaderboard entry
type LeaderboardEntry struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance uint64 `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (m *LeaderboardEntry) Reset()         { *m = LeaderboardEntry{} }
func (m *LeaderboardEntry) String() string { return proto.CompactTextString(m) }
func (*LeaderboardEntry) ProtoMessage()    {}

// QueryKudosLeaderboardResponse is the response for leaderboard query
type QueryKudosLeaderboardResponse struct {
	Entries []LeaderboardEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries"`
}

func (m *QueryKudosLeaderboardResponse) Reset()         { *m = QueryKudosLeaderboardResponse{} }
func (m *QueryKudosLeaderboardResponse) String() string { return proto.CompactTextString(m) }
func (*QueryKudosLeaderboardResponse) ProtoMessage()    {}

// KudosHistory stores a single kudos transaction
type KudosHistory struct {
	FromAddress string `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty" yaml:"from_address"`
	ToAddress   string `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty" yaml:"to_address"`
	Amount      uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Comment     string `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Timestamp   int64  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *KudosHistory) Reset()         { *m = KudosHistory{} }
func (m *KudosHistory) String() string { return proto.CompactTextString(m) }
func (*KudosHistory) ProtoMessage()    {}

func init() {
	proto.RegisterType((*QueryKudosBalanceRequest)(nil), "kudos.QueryKudosBalanceRequest")
	proto.RegisterType((*QueryKudosBalanceResponse)(nil), "kudos.QueryKudosBalanceResponse")
	proto.RegisterType((*QueryKudosLeaderboardRequest)(nil), "kudos.QueryKudosLeaderboardRequest")
	proto.RegisterType((*LeaderboardEntry)(nil), "kudos.LeaderboardEntry")
	proto.RegisterType((*QueryKudosLeaderboardResponse)(nil), "kudos.QueryKudosLeaderboardResponse")
	proto.RegisterType((*KudosHistory)(nil), "kudos.KudosHistory")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
type QueryClient interface {
	// KudosBalance queries the kudos balance of an address
	KudosBalance(ctx context.Context, in *QueryKudosBalanceRequest, opts ...grpc.CallOption) (*QueryKudosBalanceResponse, error)
	// KudosLeaderboard queries the top kudos receivers
	KudosLeaderboard(ctx context.Context, in *QueryKudosLeaderboardRequest, opts ...grpc.CallOption) (*QueryKudosLeaderboardResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) KudosBalance(ctx context.Context, in *QueryKudosBalanceRequest, opts ...grpc.CallOption) (*QueryKudosBalanceResponse, error) {
	out := new(QueryKudosBalanceResponse)
	err := c.cc.Invoke(ctx, "/kudos.Query/KudosBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) KudosLeaderboard(ctx context.Context, in *QueryKudosLeaderboardRequest, opts ...grpc.CallOption) (*QueryKudosLeaderboardResponse, error) {
	out := new(QueryKudosLeaderboardResponse)
	err := c.cc.Invoke(ctx, "/kudos.Query/KudosLeaderboard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// KudosBalance queries the kudos balance of an address
	KudosBalance(context.Context, *QueryKudosBalanceRequest) (*QueryKudosBalanceResponse, error)
	// KudosLeaderboard queries the top kudos receivers
	KudosLeaderboard(context.Context, *QueryKudosLeaderboardRequest) (*QueryKudosLeaderboardResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) KudosBalance(ctx context.Context, req *QueryKudosBalanceRequest) (*QueryKudosBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KudosBalance not implemented")
}

func (*UnimplementedQueryServer) KudosLeaderboard(ctx context.Context, req *QueryKudosLeaderboardRequest) (*QueryKudosLeaderboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KudosLeaderboard not implemented")
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_KudosBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryKudosBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).KudosBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kudos.Query/KudosBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).KudosBalance(ctx, req.(*QueryKudosBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_KudosLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryKudosLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).KudosLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kudos.Query/KudosLeaderboard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).KudosLeaderboard(ctx, req.(*QueryKudosLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kudos.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KudosBalance",
			Handler:    _Query_KudosBalance_Handler,
		},
		{
			MethodName: "KudosLeaderboard",
			Handler:    _Query_KudosLeaderboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kudos/query.proto",
}
