// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: kudos/query.proto

package types

import (
	"context"
	"io"

	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/status"
)

var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = grpclog.Printf

func RegisterQueryHandlerClient(ctx context.Context, mux *runtime.ServeMux, client QueryClient) error {
	if err := RegisterQueryHandlerFromEndpoint(ctx, mux, "", []grpc.DialOption{grpc.WithInsecure()}); err != nil {
		return err
	}
	return nil
}

func RegisterQueryHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) error {
	// This is a simplified implementation
	return nil
}
