// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kudos/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.GoGoProtoPackageIsVersion3

// MsgSendKudos represents a message to send kudos
type MsgSendKudos struct {
	FromAddress string `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty" yaml:"from_address"`
	ToAddress   string `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty" yaml:"to_address"`
	Amount      uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Comment     string `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (m *MsgSendKudos) Reset()         { *m = MsgSendKudos{} }
func (m *MsgSendKudos) String() string { return proto.CompactTextString(m) }
func (*MsgSendKudos) ProtoMessage()    {}

// MsgSendKudosResponse is the response for SendKudos
type MsgSendKudosResponse struct {
}

func (m *MsgSendKudosResponse) Reset()         { *m = MsgSendKudosResponse{} }
func (m *MsgSendKudosResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSendKudosResponse) ProtoMessage()    {}

func init() {
	proto.RegisterType((*MsgSendKudos)(nil), "kudos.MsgSendKudos")
	proto.RegisterType((*MsgSendKudosResponse)(nil), "kudos.MsgSendKudosResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
type MsgClient interface {
	// SendKudos sends kudos from one address to another
	SendKudos(ctx context.Context, in *MsgSendKudos, opts ...grpc.CallOption) (*MsgSendKudosResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SendKudos(ctx context.Context, in *MsgSendKudos, opts ...grpc.CallOption) (*MsgSendKudosResponse, error) {
	out := new(MsgSendKudosResponse)
	err := c.cc.Invoke(ctx, "/kudos.Msg/SendKudos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// SendKudos sends kudos from one address to another
	SendKudos(context.Context, *MsgSendKudos) (*MsgSendKudosResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SendKudos(ctx context.Context, req *MsgSendKudos) (*MsgSendKudosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendKudos not implemented")
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SendKudos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSendKudos)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SendKudos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kudos.Msg/SendKudos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SendKudos(ctx, req.(*MsgSendKudos))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kudos.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendKudos",
			Handler:    _Msg_SendKudos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kudos/tx.proto",
}
